### ISSUE TITLE
why "poolbase::open" doesn't change its member in place when called as a member funtion of a pool object?

### ISSUE THREAD

**Issue by wc222** [pmem/libpmemobj-cpp#1046]
# QUESTION: 

## Details

When I am using the pool library of libpmemobj++, I writing the following code intuitively:
```cpp
pool<some_type> pop;
pop.open(path, layout);
```
However, `pop.hanlde()` is still `nullptr` even if `open` doesn't throw a exception. And I found I need to write the second line as below after I read the source code of pool.hpp.
```cpp
pop = pop.open(path, layout); // or pop = poolbase::open(path, layout);
```
I wonder the reason for this design. Thanks.

**Comment by KFilipek** [comment]
Hi!
open() is a static function, so cannot set a object field.
```
	static pool<T>
	open(const std::string &path, const std::string &layout)
	{
		return pool<T>(pool_base::open(path, layout));
	}
```
In C++ you can invoke that function in both ways, `obj.open(arg1, arg2);` or `class<type>::open(arg1, arg2);`
Maybe better is in your case:
`pool<some_type> pop = pool<some_type>::open(path, layout);`

I agree, it's not as intuitive as should be.

**Comment by wc222** [comment]
Oh! Got it! The explanation is very clear. Thanks very much
