### ISSUE TITLE
Extend docs for tx (especially tx::manual)

### ISSUE THREAD

**Issue by jan-konczak-cs-put** [pmem/libpmemobj-cpp#1061]
# ISSUE: starting one manual transactions throws after another was committed in the same or higher scope

## Environment Information

- libpmemobj-cpp version(s): 1.12
- compiler, libraries, packaging and other related tools version(s): gcc-10

## Please provide a reproduction of the bug:

The problem is pretty simple: if one creates a manual transaction, commits it and then tries to start another manual or automatic transaction without exiting the scope, then upon starting the second one an exception is raised. See the following example:

```#include <filesystem>
#include <libpmemobj++/pool.hpp>
#include <libpmemobj++/persistent_ptr.hpp>
#include <libpmemobj++/transaction.hpp>

namespace pm = pmem::obj;

struct root {
    pm::p<int> foo;
};

int main(int argc, char ** argv){
    const char * poolFile = argc>1?argv[1]:"/mnt/pmem/pool";
    auto pop = pm::pool<root>::create(poolFile, std::string{}, PMEMOBJ_MIN_POOL);
    std::filesystem::remove(poolFile);
    
    pm::transaction::manual t1(pop);
    pop.root()->foo=1;
    pm::transaction::commit();
    
    // line below throws
    pm::transaction::manual t2(pop);
    pop.root()->foo=2;
    pm::transaction::commit();
    
    return 0;
}
```
## How often bug is revealed:

always

## Actual behavior:

```
terminate called after throwing an instance of 'pmem::transaction_scope_error'
  what():  Cannot start transaction in stage different than WORK or NONE
```

## Expected behavior:

no error

## Details

It seems that a transaction finishes up upon calling the destructor, not upon a `commit()`.

If one would do:
```
    pm::transaction::manual tx(pop);
    …
    pm::transaction::commit();

    foo();
```
and `foo()` would try to start an automatic or manual transaction, same problem happens - an exception is raised.

**Comment by igchor** [comment]
This is actually expected, however I we should definitely extend our docs for manual tx.

Basically, the job of a destructor is to release any locks (if held). The reason is that you might want to perform some operations after commit but when locks are still held.

In general, I think using transaction::run() and passing a lambda is simpler and less error-prone approach.
