### ISSUE TITLE
make_persistent on linux

### ISSUE THREAD

**Issue by weishuo2** [pmem/libpmemobj-cpp#1068]
# QUESTION: 

## Details
How can I allocate byte array on NVM？

PMDKso.cpp:48:50: 错误：对‘make_persistent(int)’的调用没有匹配的函数
         proot->buf = make_persistent<byte[]>(1000);
In file included from PMDKso.cpp:1:0:
/usr/local/include/libpmemobj++/make_persistent.hpp:75:1: 附注：candidate: template<class T, class ... Args> typename pmem::detail::pp_if_not_array<T>::type pmem::obj::make_persistent(Args&& ...)
 make_persistent(Args &&... args)

**Comment by igchor** [comment]
Hi @weishuo2,

`proot->buf = make_persistent<byte[]>(1000);` line should work given `proot->buf` is `persistent_ptr<byte[]>`.
Could you share your entire error message and code?

In previous versions of libpmemobj-cpp you had to to manually include "libpmemobj++/make_persistent_array.hpp". You can try doing this.

**Comment by weishuo2** [comment]
ok，Problem has been solved ，thank you.
