### ISSUE TITLE
symbol pmemobj_set_user_data not define

### ISSUE THREAD

**Issue by weishuo2** [pmem/libpmemobj-cpp#1071]
I called libpmembobj++ to write a dynamic library, and then used C# to call the dynamic library. 
When running in C#, it appears: symbol pmemobj_set_user_data, version LIBPMEMOBJ_1.0 not defined in file libpmemobj.so.1 with link time reference .
I am curious what the problem is and how to solve it .Looking forward to your reply.

**Comment by pbalcer** [comment]
This function was added in libpmemobj 1.8, and your application is likely linking with something older.

**Comment by weishuo2** [comment]
g++ PMDKso_nvm.cpp -fPIC -shared -o PMDKso_nvm.so -L/usr/local/lib64 -lpmemobj -std=c++11
The version of libpmemobj under /usr/local/lib64 is 1.9,but this doesn't seem to work.
And I found that it was linking to libpmemobj installed by yum whose version is 1.5 .
Could you please tell me what should I do and when should I link it？

**Comment by weishuo2** [comment]
I found the problem and solved it ，Need to change LD_LIBRARY_PATH, it is useless to modify the link when compiling the dynamic library, because the lib called at runtime and the lib when compiling the dynamic library are not the same .
Thank you .
