### ISSUE TITLE
How to use `initializer_list` constructor for vector?

### ISSUE THREAD

**Issue by marvinruder** [pmem/libpmemobj-cpp#1089]
# QUESTION: How to use `initializer_list` constructor for vector?

## Details

I am trying to initialize a vector of `int8_t`s using the `vector(std::initializer_list<T> init);` constructor (from [`vector.hpp:72`](https://github.com/pmem/libpmemobj-cpp/blob/98e0461c63b8d2b69bfc8f4d8932c2156aa9b4cb/include/libpmemobj%2B%2B/container/vector.hpp#L72)). The results are as follows:

```
pmem::obj::persistent_ptr<pmem::obj::vector<int8_t>> ptr;
ptr = pmem::obj::make_persistent<pmem::obj::vector<int8_t>>((std::initializer_list<int8_t>){ 7, 5, 16, 8 }); // works fine
ptr = pmem::obj::make_persistent<pmem::obj::vector<int8_t>>({ 7, 5, 16, 8 }); // compiler error: no matching function for call to ‘make_persistent<pmem::obj::vector<int8_t>>(<brace-enclosed initializer list>)’
```

Is there any way to use a brace-enclosed initializer list without explicitly stating that it is a initializer list?

**Comment by igchor** [comment]
Hi @marvinruder,

Unfortunately this is not possible - make_persistent is not able to deduce the initializer_list type. It is the same problem as for example with std::make_unique. You can find some workarounds (similar to yours) here: https://stackoverflow.com/questions/26379311/calling-initializer-list-constructor-via-make-unique-make-shared.

**Comment by igchor** [comment]
There is no way (I know of) to make it work for make_peristent so I will close this issue. If you have any ideas or suggestions for improving/extending the API feel free to reopen it.
