### ISSUE TITLE
Error while installation of libpmemobj-cpp.

### ISSUE THREAD

**Issue by Derejereg** [pmem/libpmemobj-cpp#1148]
# QUESTION: 

## Details: I already installed the pmdk tagged with version 1.11.0 and set the environment variables as per the installation guides of pmdk. When I install libpmemobj-cpp, on Ubuntu Server 20.04 LTS, I got an error message as follows. 

-- Performing Test CXX_HAS__DLIBPMEMOBJ_CPP_VG_PMEMCHECK_ENABLED_1 - Success
-- Found clang: /usr/bin/clang (version: )
-- Checking for module 'libpmemobj>=1.9'
--   Package 'libpmemobj', required by 'virtual:world', not found
CMake Error at /usr/local/share/cmake-3.21/Modules/FindPkgConfig.cmake:572 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.21/Modules/FindPkgConfig.cmake:794 (_pkg_check_modules_internal)
  CMakeLists.txt:149 (pkg_check_modules)

I also tried to search for the required libpmemobj with version >1.9, but couldn't get it for the above server version. Is there someone who can guide me to install this without error?

**Comment by igchor** [comment]
Hi,

libpmemobj-cpp relies on pkg-config for finding PMDK (libpmemobj). Does `pkg-config --modversion libpmemobj` work and return proper version? If not you need to set the PKG_CONFIG_PATH to proper directory (e.g. `/home/my/install_dir/lib/pkgconfig`)

**Comment by lukaszstolarczuk** [comment]
Hi @Derejereg , do you still need any assistance with our library usage? Please let us know if we can help you.
