### ISSUE TITLE
Missing 1.5 documentation

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/libpmemobj-cpp#115]
gh-pages branch doesn't have stable-1.5 directory.
http://pmem.io/pmdk/cpp_obj/ links to master documentation.

**Comment by igchor** [comment]
Documentation is already merged: #269
Change to pmdk (to add links) is under review: pmem/pmdk#3643

**Comment by marcinslusarz** [comment]
1.5 and 1.6 are fine, now the same problem exists for 1.7.

**Comment by lukaszstolarczuk** [comment]
Fixed, all documentation is there: https://pmem.io/libpmemobj-cpp/
