### ISSUE TITLE
Undefined reference to 'pmemobj_tx_set_failure_behavior'

### ISSUE THREAD

**Issue by astromonkeys** [pmem/libpmemobj-cpp#1186]
######

I'm relatively new to GitHub, so if I'm not providing all necessary information/going against etiquette I apologize!

######

# ISSUE: Undefined reference to 'pmemobj_tx_set_failure_behavior'

## Environment Information

- libpmemobj-cpp version(s):                                         1.13.0
- PMDK (libpmemobj) package version(s):                              1.11.0
- OS(es) version(s):                                                 Ubuntu 20.04
- kernel version(s):                                                 5.4.0-77-generic
- compiler, libraries, packaging and other related tools version(s): G++ 11.1.0

and possibly:
- TBB version(s):                                                    
- ndctl version(s):                                                  67-1

## Please provide a reproduction of the bug:

string_struct_example.cpp is a simple example of persisting a string using a transaction. The compiler does not give any errors/warnings, but the linker fails(see actual behavior). Source code is attached as a txt file
[string_struct_example.txt](https://github.com/pmem/libpmemobj-cpp/files/6919600/string_struct_example.txt)
.

Compiled using:
g++ -o string_struct_example string_struct_example.cpp -lpmemobj -g

Leads to linking error.

## How often bug is revealed:

Always. Every time I attempt to compile a source file that uses transactions.

## Actual behavior:

Failure during linking:
/usr/bin/ld: /tmp/cc65ooHg.o: in function `std::enable_if<true, void>::type pmem::detail::transaction_base<true>::manual::set_failure_behavior<true>()':
/usr/local/include/libpmemobj++/transaction.hpp:145: undefined reference to `pmemobj_tx_set_failure_behavior'
collect2: error: ld returned 1 exit status

## Expected behavior:

Successful compilation, or at least an error in my own code that I can fix

## Details

For some reason the linker cannot find the definition for this function. I'm not sure why, since tx_base.h and transaction.hpp are both present

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? **No**

Requested priority: (Showstopper, High, Medium, Low)                        High. I cannot continue my internship work without this fixed!

**Comment by lukaszstolarczuk** [comment]
Hi,
I can see you posted a version of PMDK as `1.11.0` - but is it possible you have installed in your system also some older PMDK libraries?

Can you please check how pkg-config sees it? Please verify the output of `pkg-config --modversion libpmemobj`.

**Comment by KFilipek** [comment]
I compiled this code without any issues.
If you get linker error it's mean that you have headers in correct paths and compilation finished successfully.
Then we should investigate few things.
- Did you installed package or compiled whole PMDK? (https://github.com/pmem/pmdk#building-pmdk-on-linux-or-freebsd)
- If compiled, did you install it with root priviledges?
- What prints pkg-config? (vide @lukaszstolarczuk post)
- Do you have packages in proper paths in ld? I believe not: `ldconfig -v | grep pmem`
- The easiest way to compile your code is to add `-L/path/to/compiled/lib_directory/`

Last thing, notice, that in transaction.hpp:150 there is no definition for function `pmemobj_tx_set_failure_behavior`, there is a call for mentioned function and this function is provided in .so package, compiled previously in PMDK.
1. Correct way is to compile PMDK, then install it
2. Install libpmemobj-cpp
3. Then compile your code
Steps 1+2 can be replaced with installing dev packages with apt, but I'm not sure there is a latest version.
