### ISSUE TITLE
[doc] Update comments in atomic_persistent_aware_ptr to hide implementation details

### ISSUE THREAD

**Issue by KFilipek** [pmem/libpmemobj-cpp#1230]
Please hide implementation details in documentation, like dirty flag, describe parameters etc.
Related file: include/libpmemobj++/experimental/atomic_persistent_aware_ptr.hpp
Related discussion: #1229

**Comment by lukaszstolarczuk** [comment]
ref. https://github.com/pmem/libpmemobj-cpp/pull/1229
