### ISSUE TITLE
Valgrind not found, but flag TESTS_USE_VALGRIND was set.

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1251]
when i installed it in centos, it appeared the problem, but i have installed valgrind, why??? thanks~~

cmake.. : 
CMake Error at CMakeLists.txt:154 (message):
  Valgrind not found, but flag TESTS_USE_VALGRIND was set.

**Comment by HBSDLJZ** [comment]
thank you~~

**Comment by lukaszstolarczuk** [comment]
I'm glad it helped. If you have any more queries don't hesitate to contact us again.

**Comment by HBSDLJZ** [comment]
![image](https://user-images.githubusercontent.com/43542395/169286545-01f24118-3e96-451a-8777-67b164061044.png)
The problem "Package 'libpmemobj' has version '1.6.1', required version is '>= 1.9'
" appeared, when I cmake libpmemobj. How can I install the version which >= 1.9, can you tell me some steps?thankyou!

**Comment by lukaszstolarczuk** [comment]
I hoped it solved the problem - closing for now.
