### ISSUE TITLE
concurrent_hash_map

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1253]
https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1concurrent__hash__map.html#afd573b5dd87d540652e9c63e9e195fd1

hello~~~
I want to study **concurrent_hash_map** structure deeply，Can you give me some detailed information, such as design?
If you can, please send it to my email or web connection~
thankyou~
--------------------hbsd_ljz@163.com

**Comment by lukaszstolarczuk** [comment]
Hi,
in [the hashmap description](https://github.com/pmem/libpmemobj-cpp/blob/master/include/libpmemobj%2B%2B/container/concurrent_hash_map.hpp#L1575) we provide two links with deeper information about the structure itself:
 - [Intel OneTBB's concurrent_hash_map](https://spec.oneapi.io/versions/0.5.0/oneTBB/containers/concurrent_hash_map_cls.html)
 - [concurrent hash table algorithm](https://arxiv.org/ftp/arxiv/papers/1509/1509.02235.pdf)

If you need deeper dive into pmem (not necessarily about concurrent hashmap) you can always look into our pmem book: https://pmem.io/books/

please let me know if that works for you.

**Comment by HBSDLJZ** [comment]
First link is "Page Not Found"
oh yeach,thank you again~

**Comment by HBSDLJZ** [comment]
thank you again~~

**Comment by lukaszstolarczuk** [comment]
yeah, sorry, mea culpa - I forgot OneTBB moved on to a new page, I fixed the first link:

https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_hash_map_cls.html

**Comment by HBSDLJZ** [comment]
thank you again~~

**Comment by lukaszstolarczuk** [comment]
👍 no problem.

Closing for now, please contact us again if you have more questions :-)

**Comment by HBSDLJZ** [comment]
When I write a large amount of data, what can I do to improve the write throughput of the hash table?
thank you~~
