### ISSUE TITLE
Read garbled code

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1254]
![image](https://user-images.githubusercontent.com/43542395/170445149-522a68c0-9fc5-403c-a0f0-03bf68aad3bc.png)

I write a piece of data to “concurrent_hash_map<p<int>, p<char*>>”，but it's garbled when read it
how to slove it，thankyou~

**Comment by lukaszstolarczuk** [comment]
Hi,

can you please share you hashmap declaration and the actual code you're using to write the data?

BTW, there's an example for concurrent hash map: https://github.com/pmem/libpmemobj-cpp/blob/master/examples/concurrent_hash_map/concurrent_hash_map.cpp

**Comment by HBSDLJZ** [comment]
Your answers are very timely every time. Thank you very much!
After writing data, comment out the code of write operation, and the code of rerun read operation will be garbled~

`#include <iostream>
#include <libpmemobj++/container/concurrent_hash_map.hpp>
#include <libpmemobj++/p.hpp>
#include <libpmemobj++/persistent_ptr.hpp>
#include <libpmemobj++/pool.hpp>
#include <vector>

using namespace pmem::obj;

using hashmap_type = concurrent_hash_map<p<int>, p<char*>>;
// pmempool create obj --layout="concurrent_hash_map" --size 1G /pmemfs0/liujinzhou/hash_pool.obj
const int THREADS_NUM = 30;
const char *path = "/pmemfs0/liujinzhou/hash_pool.obj";

struct root {
  persistent_ptr<hashmap_type> pptr;
};

int main() {
  pool<root> pop;
  try {
    pop = pool<root>::open(path, "concurrent_hash_map");
  } catch (pmem::pool_error &e) {
    std::cerr << e.what() << std::endl;
    return -1;
  }
  try {
    auto &r = pop.root()->pptr;

    if (r == nullptr) {
      pmem::obj::transaction::run(pop, [&] {
        r = make_persistent<hashmap_type>();
      });
      r->runtime_initialize();
    } else {
      r->runtime_initialize();
      try {
        r->defragment();
      } catch (const pmem::defrag_error &e) {
        std::cerr << "Defragmentation exception:" << e.what() << std::endl;
        throw;
      }
    }

    auto &map = *r;
    std::cout << map.size() << std::endl;

    char *value = "wuzimadashu";
    map.insert_or_assign(2016011493, value);

    hashmap_type::const_accessor acc;
    bool res = map.find(acc, 2016011493);
    if (res) {
      std::cout << acc->first << " : " << acc->second << std::endl;
    }
  } catch (std::exception &e) {
    std::cerr << "Exception occurred: " << e.what() << std::endl;
  }
  try {
    pop.close();
  } catch (const std::logic_error &e) {
    std::cerr << "Exception: " << e.what() << std::endl;
    return -1;
  }
  return 0;
}
`

**Comment by HBSDLJZ** [comment]
using hashmap_type = concurrent_hash_map<p, p<char*>>;

char *value = "wuzimadashu";
map.insert_or_assign(2016011493, value);

then, run again "bool res = map.find(acc, 2016011493);"

**Comment by lukaszstolarczuk** [comment]
Without executing into your code I'd say - I'm not sure if `p` class works with `char *` type. I believe you should try using our pmem string (as in our second hashmap example: https://github.com/pmem/libpmemobj-cpp/blob/master/examples/concurrent_hash_map/concurrent_hash_map_string.cpp) or maybe an array of `p<char>` (but not sure if that will work well with hashmap).

**Comment by HBSDLJZ** [comment]
oh, yeach~
Thanks for help me solving the problem again!

**Comment by lukaszstolarczuk** [comment]
I'm glad I could help :)

I'm closing this issue, for now. If you have any more questions don't hesitate to contact us again.
