### ISSUE TITLE
using hashmap_type = concurrent_hash_map<string, p<int>>;

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1256]
using hashmap_type = concurrent_hash_map<string, p<int>>;

![image](https://user-images.githubusercontent.com/43542395/172868532-69966c84-f510-4073-8942-52793b36adcc.png)

"defragment()" Prompt: i cannot store string type keys. how can i store string type keys??

**Comment by igchor** [comment]
What is the issue you're having with storing string keys? Are you getting some compile/runtime errors?

You might need to provide hasher for the string - please take a look here: https://github.com/pmem/libpmemobj-cpp/blob/master/tests/concurrent_hash_map/concurrent_hash_map_string_test.hpp

**Comment by HBSDLJZ** [comment]
nice thankyou～

**Comment by igchor** [comment]
Feel free to reopen the issue if you have any more problems
