### ISSUE TITLE
Why do not make install?

### ISSUE THREAD

**Issue by EasyLuck** [pmem/libpmemobj-cpp#1257]
# QUESTION: 

## Details
Why do not make install after make, then how can program find the poem lib when develop app.

**Comment by igchor** [comment]
I'm not sure if I understand the question. Do you have any problems with the installation of libpmemobj-cpp?

libpmemobj-cpp can be installed as described here: https://github.com/pmem/libpmemobj-cpp#standard-compilation
Some OSes also provide packages with libpmemobj-cpp which you can install (e.g. by using apt or dnf)

**Comment by lukaszstolarczuk** [comment]
> Why do not make install after make, then how can program find the poem lib when develop app.

As you expect properly, you have to install pmem libraries somehow (and somewhere) in your system to be able to run your apps with our libs. (please follow igchor's suggestion)

If there's some information saying "you shouldn't install", please let us know - maybe we wrote something improperly in our docs...?

**Comment by EasyLuck** [comment]
Yes, I understand that now. Thank you very much.
