### ISSUE TITLE
ndctl create-namespace

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1260]
{
"regions":[
{
"dev":"region1",
"size":270582939648,
"align":16777216,
"available_size":270582939648,
"max_available_extent":270582939648,
"type":"pmem",
"iset_id":4649103193157805124,
"persistence_domain":"memory_controller"
},
{
"dev":"region0",
"size":270582939648,
"align":16777216,
"available_size":270582939648,
"max_available_extent":270582939648,
"type":"pmem",
"iset_id":4649103193157805124,
"persistence_domain":"memory_controller"
},
]
}
ndctl create-namespace:
I want to create a 512GB namespace, but I have two 256 pmem regions. How do I create them? My scenario is to create a mapping file with a size of 512GB.
Thank you~

**Comment by lukaszstolarczuk** [comment]
Hi,
AFAIK, you can't create one namespace spanning two regions, you can do either:
- delete existing regions (goals), create one big region (I'm guessing using the Interleaved mode) and create one requested namespace on the bigger region,
- create 2 smaller namespaces (on the existing regions) and use them in some kind of RAID, I guess.

Some links you may find useful, for more details:
- https://github.com/intel/ipmctl/issues/107
- https://docs.pmem.io/ndctl-user-guide/
- https://github.com/pmem/ndctl

**Comment by HBSDLJZ** [comment]
thankyou
