### ISSUE TITLE
radix-tree

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1270]
Through which API can I know how much NVM space my radix-tree occupies?

Can you give me a more detailed radix-tree design? I want to know more about this data structure.

**Comment by igchor** [comment]
Hi, unfortunately, there is no easy way to figure out how much space is actually used. Please refer here for more details:https://github.com/pmem/pmemkv/issues/671

Here is a document that describes radix tree in more detail (from page 29): https://github.com/chorig9/Persistent_Memory_Programming/blob/main/Persistent%20Memory%20Programming.pdf

**Comment by HBSDLJZ** [comment]
oh，thanks！

**Comment by lukaszstolarczuk** [comment]
I believe it can be closed. If you feel like asking more questions, please re-open.
