### ISSUE TITLE
Can it be used and built with Mingw64 in MSYS2

### ISSUE THREAD

**Issue by lonnietc** [pmem/libpmemobj-cpp#1274]
Hello,

I am looking to develop a project that might use PMEM capabilities.

The project will be for Windows, Linux, and MacOS (later) and I would like to be able to use the library from within the MSYS2 environment that compiles using Mingw64 and produces appropriate Windows EXE files.

Can the library be used with Mingw64?
Thanks

**Comment by lukaszstolarczuk** [comment]
Hey, I'm closing this issue for now. If you have any more queries, please re-open or just file another issue.
