### ISSUE TITLE
cannot build from github - 'Is a directory'

### ISSUE THREAD

**Issue by cinderwalk** [pmem/libpmemobj-cpp#297]
The version of this library in Debian is old. I tried compiling source downloaded from github, but it doesn't compile, with error message:
/usr/bin/ld: cannot open output file concurrent_hash_map_singlethread: Is a directory

**Comment by kilobyte** [comment]
If you have libpmemobj-cpp at all, you're running Debian Buster (testing) or unstable.  On both of those, version 1.6 from experimental works without a need for backporting.

As for the build failure: the usual mode of compilation (so-called "in-tree") indeed doesn't work — you need to create a directory somewhere then pass the original top dir to cmake.

**Comment by cinderwalk** [comment]
The version in experimental is for amd64 only. Will it work elsewhere in the future?

**Comment by kilobyte** [comment]
It'd be better if you could open a new issue for separate questions.

Out of curiosity, may I ask what would you want portability for?  This way I'd be able to provide a more meaningful answer.

If you mean "elsewhere" as in "other architectures", then libpmemobj-cpp by itself has no arch-dependant pieces other than a reliance on 64-bit words.  When you have 6TB memory to mmap, a limit of 32 bits would be pretty ridiculous.  On the other hand, for any heavy lifting this library uses PMDK, which is currently pretty much amd64 only.  As for other archs:
 * arm64: there's some preliminary support, although not working at the moment
 * riscv64: according to folks on #riscv64 IRC, the architecture doesn't even have cache control instructions (its designers want cache to be fully transparent), thus there's no obvious way for PMDK to function
 * ppc64{,el}: support seems possible; I may ask a ppc person who deals with related areas like ndctl
 * mips64: the architecture seems to be dying — by the time you implement, test and deploy whatever project you're planning, it's very unlikely there'll be distribution support, etc, for the arch
 * ia64: the Itanic has sank ages ago.  While technically Intel still sells new CPUs, no one uses them for new deployments.
 * s390x: it's an extremely niche architecture, sold by IBM for the sake of a limited number of lucrative clients.  Thus, unless you're specifically paid to do so, I'd recommend waiting for someone from IBM to do any porting.

Thus: do you have any real use case, or do you want portability for portability sake?  There's development cost involved, and I wonder what you'd gain.

**Comment by lukaszstolarczuk** [comment]
Hi @cinderwalk, it's been a while since your last update, so I assume all your questions has been answered...? I allow myself to close this issue. If you have any more comments or questions don't hesitate to open another issue.
