### ISSUE TITLE
FEAT: C++ Persistent Containers

### ISSUE THREAD

**Issue by pbalcer** [pmem/libpmemobj-cpp#305]
# C++ Persistent Containers for 1.6

This is a meta-issue for `pmem::vector`, `pmem::string`, `pmem::map`, and `pmem::unordered_map`.

## Rationale
Our C++ bindings cannot be easily used with any existing implementations of basic containers like vector, string or a map. This means that users are effectively left on their own.

## Description
We should implement C++ containers are tailored made and optimized for persistent memory. They should be modeled after the STL containers, so that the standard algorithms work, but they won't be drop-in replacements.
We should also provide convenient and safe way of accessing data from those containers. Non-const iterators should automatically snapshot elements in reasonable chunks, and we should also provide a way to access only a range of data from a containers, so that we need to snapshot less.

## API Changes
No visible changes.

**Comment by seghcder** [comment]
I think the basic ones are done and then some more too ... is there still a plan to do map/unordered map? Concurrent hashmap is good but also seems to consume a lot more space & have more complexity eg with the defrag requirement. If map/unordered map help with that then might be good?

https://github.com/pmem/libpmemobj-cpp/projects/3

Others might be 
* list - I think there was a v early example before vector?
* deque - particularly good for rolling timeseries? And can be adapted for other types of queues

**Comment by igchor** [comment]
I agree that concurrent hashmap/map is quite heavy but right now, there is no plan to implement more containers. 

As for deque - I think that our [pmem::obj::segment_vector ](https://github.com/pmem/libpmemobj-cpp/blob/master/include/libpmemobj%2B%2B/container/segment_vector.hpp) could be a good base for it.
