### ISSUE TITLE
cpp: CTL/allocation flags

### ISSUE THREAD

**Issue by pbalcer** [pmem/libpmemobj-cpp#308]
CTL APIs are currently not exposed to the C++ bindings. We need to create convenience wrappers around them, and maybe create an abstraction for allocation classes.
We will also need to allow allocating from custom allocation classes - could be as simple as exposing the flags field, but we might also do a larger wrapper.

**Comment by lukaszstolarczuk** [comment]
it's exposed in `ctl.hpp`
