### ISSUE TITLE
Fix Windows warnings

### ISSUE THREAD

**Issue by ldorau** [pmem/libpmemobj-cpp#409]
There are:
503 warnings #C4800
156 warnings #C4996
13 warnings #C4101
12 warnings #C4673
12 warnings #C4672
8 warnings #C4267
7 warnings #C4100
4 warnings #C4521
2 warnings #C4244
in the build:
https://ci.appveyor.com/project/pmem/libpmemobj-cpp/builds/27203871/job/4xyag281wv4ih2ah

**Comment by lukaszstolarczuk** [comment]
Currently there are 209 warnings in total, see e.g.:
https://github.com/pmem/libpmemobj-cpp/runs/784225708 (**Build** section)

**Comment by seghcder** [comment]
Am seeing warning `C4244: 'initializing': conversion from 'double' to 'size_t', possible loss of data` at W2 level on

https://github.com/pmem/libpmemobj-cpp/blob/12c98c1d7a3780ca37c96fcc8124c720887066d0/include/libpmemobj%2B%2B/container/concurrent_hash_map.hpp#L2839-L2840

Perhaps warning levels W2/W3 could be Priority 2/3 and P4 be priority 4? Default MSVC CMake setting is W3.

**Comment by igchor** [comment]
We mostly rely on warning from -Wall (and some additional ones) from gcc and clang. We do not look at the windows ones much. I think we could set it to W2 and also enable WX after we fix them.

**Comment by seghcder** [comment]
I worry somewhat about mixing reals and integrals and loss of data in a function like a defragger! One unexpected edge case and you end up with https://www.youtube.com/watch?v=eXKE0nAMmg4!

Sounds good re W2/WX. Am switching to Windows & MSVC for a while to increase multiplatform support.

**Comment by igchor** [comment]
Right, we would not like for anything like that to happen :d

And actually, you are right that this cast could make some problems, e.g. if due to rounding errors we'd end up with an index larger than number of elements in the hashmap.
