### ISSUE TITLE
cmake failed in libpmemobj++ despite having latest pmdk

### ISSUE THREAD

**Issue by elnasabdallah** [pmem/libpmemobj-cpp#501]
`nasir@Nasir-HP-Notebook:~/libpmemobj-cpp/build$ cmake ..
-- Checking for module 'libpmemobj>=1.7'
--   Requested 'libpmemobj >= 1.7' but version of libpmemobj is 1.4.1
You may find new versions of libpmemobj at http://pmem.io/pmdk
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:131 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/nasir/libpmemobj-cpp/build/CMakeFiles/CMakeOutput.log".
See also "/home/nasir/libpmemobj-cpp/build/CMakeFiles/CMakeError.log".
`

I keep receiving the above, i deleted my previous pmdk and cloned new one yet the error persists.

**Comment by igchor** [comment]
Hi,

is it possible that you have installed pmdk using package manager in your distribution? If so, try removing it. You can also try setting env PKG_CONFIG_PATH variable to point to pmdk's installation directory in which *.pc files are located. For example:

```
...
PKG_CONFIG_PATH=/home/elnasabdallah/pmdk/lib/pkgconfig cmake ..
```

**Comment by igchor** [comment]
I'll close this issue for now, please feel free to reopen if you still have any problems
