### ISSUE TITLE
Misleading Pool operation

### ISSUE THREAD

**Issue by PhilippGoetze** [pmem/libpmemobj-cpp#524]
The pool operation for persisting a persistent_ptr is a bit misleading.
The comment states that it would persist a persistent object. Instead, it is persisting the pointer, not the object. 
https://github.com/pmem/libpmemobj-cpp/blob/9ad4b1c030bea89ac45fef50b07ff6b7042f2ae1/include/libpmemobj%2B%2B/pool.hpp#L305-L315

Is this intended? I would have expected rather something like the following:
```C++
pmemobj_persist(this->pop, &*ptr, sizeof(Y)); 
```
Or would this be problematic for some object types (Y)?

**Comment by igchor** [comment]
This is actually intended but I agree that this may be misleading - we'll extend the description. This persist method is helpful if you want to modify the pointer itself. For persisting objects which are pointed by persistent_ptr there is `persist` function inside persistent_ptr class:

https://github.com/pmem/libpmemobj-cpp/blob/9ad4b1c030bea89ac45fef50b07ff6b7042f2ae1/include/libpmemobj%2B%2B/persistent_ptr.hpp#L268-L277

**Comment by PhilippGoetze** [comment]
Thanks for the hint to the persist function within persistent_ptr. I wasn't aware of this.
`pptr.persist(pop)` also looks cleaner in the code than `pop.persist(&*pptr, sizeof(...))`.
