### ISSUE TITLE
why this lib must rely on intel TBB lib?

### ISSUE THREAD

**Issue by gwnet** [pmem/libpmemobj-cpp#689]
CMake Warning at cmake/tbb.cmake:11 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:163 (include)

**Comment by igchor** [comment]
The tbb dependency is entirely optional (it is used in some of our tests). The message you get is only a warning, not error.

**Comment by lukaszstolarczuk** [comment]
It looks like this question was answered. If you want to discuss anything more, please open another issue.
