### ISSUE TITLE
build error on SLES12SP4 for examples code

### ISSUE THREAD

**Issue by gwnet** [pmem/libpmemobj-cpp#713]
I have build all other PMDK related codes with my cmake, only this examples has issue.

murray-rust:/tmp/wayne/pmem/skiplist/libpmemobj-cpp/examples/build # cmake  -D CMAKE_C_COMPILER=/usr/bin/gcc-5 -D CMAKE_CXX_COMPILER=/usr/bin/g++-5 ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:7 (add_flag):
  Unknown CMake command "add_flag".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.17)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/tmp/wayne/pmem/skiplist/libpmemobj-cpp/examples/build/CMakeFiles/CMakeOutput.log".
murray-rust:/tmp/wayne/pmem/skiplist/libpmemobj-cpp/examples/build # cmake --version
cmake version 3.17.20200312-g9fd5ca4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
murray-rust:/tmp/wayne/pmem/skiplist/libpmemobj-cpp/examples/build #

**Comment by karczex** [comment]
Are we going to support suse?

**Comment by lukaszstolarczuk** [comment]
@karczex, I believe we are supporting SUSE in some degree - OpenSuse build is green on CI :)


Anyway, @gwnet, I took a look at this issue once more and I'm not sure if we want to support this precise behavior:
`libpmemobj-cpp/examples/build # cmake ..`

It would mean we treat examples directory as a separate project/executable, which we don't. We use CMakeLists.txt in this dir to use in top-level CMake (e.g. to include examples targets and find necessary packages for examples). We allow standalone builds of examples and there is a separate CMakeLists.txt in each and every example's dir - to build such you have to go one level deeper, e.g.:
`libpmemobj-cpp/examples/array/build # cmake ..` to build array example (standalone project, which requires installed package of libpmemobj-cpp in the system)

To build all examples at once, as a part of libpmemobj-cpp project (not standalone projects) just prepare main project's build and make all examples, like:

```
libpmemobj-cpp/build # cmake .. -DBUILD_EXAMPLES=ON
libpmemobj-cpp/build # make examples
```

If you have any more comments, please let us know. If not I'll probably close this issue in some time :)

**Comment by lukaszstolarczuk** [comment]
If you believe this is still a problem, please don't hesitate and open new issue.
