### ISSUE TITLE
can't build the project

### ISSUE THREAD

**Issue by BLOODButter** [pmem/libpmemobj-cpp#739]
when i run "make", it shows me this,it says "Linking CXX executable ex-queue
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'"
![TIM图片20200503125326](https://user-images.githubusercontent.com/45619350/80899003-13a01080-8d3d-11ea-933f-5ffbcc815402.png)

did i forgot to install some packages?

**Comment by igchor** [comment]
Could you please provide the full Cmake log? What OS and compiler are you using?

**Comment by lukaszstolarczuk** [comment]
Hi @BLOODButter, it's been a while since your last update, so I assume this is not a problem anymore...? Please provide more info if it still occurs.

I'll wait for another week and then allow myself to close this issue.
