### ISSUE TITLE
Timeline for advanced container development 

### ISSUE THREAD

**Issue by mengranwo** [pmem/libpmemobj-cpp#749]
Not sure if this is the right place to ask questions regards the development cycle, but I was wondering is advanced container **pmem::obj::map** still on the table? If yes, then do we have an estimated timeline/release version for this feature? 

thank you!

**Comment by szyrom** [comment]
Hi mengranwo,

It is on the table, and we are currently working on pathfinding for the most efficient data structure (which will be also suitable for the implementation of pmem::ob:j:map/set/multimap/multiset). As a result of the pathfinding phase, we want to publish a single-threaded, sorted engine in pmemkv (https://github.com/pmem/pmemkv) and we are close to finishing this assignment (see draft pull request for B-tree https://github.com/pmem/pmemkv/pull/681). After that we will work on libpmemobj-cpp version of this structure with all the necessary methods (like in std::map).

The next libpmemobj-cpp release (v1.10) is scheduled for the end of this month (May). We can prioritize implementation of pmem::obj::map for the 1.11 release (maybe without all the supported methods and/or without multimap/multiset/set variants). The priority of the backlog features is driven by our customers' requirements so it will be good to know your actual background and story (we can move this conversion to the email thread if you want: szymon.romik@intel.com). 

PMDK (and libpmemobj-cpp) is the open-source project, so any external contribution is more than welcome.

**Comment by mengranwo** [comment]
@szyrom 
Hey, thank you for sharing the future release timeline. We've sent out an email (about 10days ago, I think) briefly introducing our background and some of the PMEM use cases, looking forward to your reply!
