### ISSUE TITLE
Altering the implementation of a class after pool creation

### ISSUE THREAD

**Issue by seghcder** [pmem/libpmemobj-cpp#783]
In several places in pmem documentation & presentations ([eg](https://www.slideshare.net/IntelSoftware/creating-c-apps-with-pmdk-piotr-balcer)) there is reference to a requirement that all objects in a pool should be reachable from the root object. In addition,  any unlinked object is effectively a persistent memory leak.

A challenge arises when one wants to add a new class to the pool. In order to maintain the root ojbect chain, an existing object in the pool would need to be updated to add a reference to the new object. In doing so, the layout of the existing object now needs to be updated. This might be one object or an entire container of objects.

This has led to an approach or workaround of maintaining separate pools to reduce change impact (eg via component approach discussed in https://github.com/pmem/libpmemobj-cpp/issues/363 [comment](https://github.com/pmem/libpmemobj-cpp/issues/363#issuecomment-636874505)), but then we run into the cross pool transaction issue (https://github.com/pmem/pmdk/issues/4198).  @pbalcer suggested we try avoid having separate pools, and this issue is investigating one approach for pool maintenance...

## Accessing a class without reference to root object chain
If one obtains the type_num (typeid::hash_code - see https://github.com/pmem/libpmemobj-cpp/issues/776) of a class, then it's also reachable via `libpmemobj.h` and `POBJ_FIRST_TYPE_NUM`. For example, this seems to work:

```c++
auto type_num = pmem::detail::type_num<MyApp>();
auto pmem_oid = POBJ_FIRST_TYPE_NUM(my_pool.handle(), type_num);
auto new_app = pmem::obj::persistent_ptr<MyApp>(pmem_oid);
```
This suggests we can add objects to the pool without updating the root object chain.

Two questions here -  
* What is the time complexity of POBJ_FIRST_TYPE_NUM and POBJ_NEXT_TYPE_NUM? It seems like it was iterating all PMEMoid's in the pool ([ref](https://github.com/pmem/pmdk/blob/0be0729b005c205cc80b3cb927a2f665801c9bc3/src/include/libpmemobj/iterator.h#L23-L25))?
* Are there any other downsides to accessing class objects this way vs through the root object chain? 
 

## Updating an existing class 
In the instance when we want to update the implementation of an existing class without invaliding the layout, here's a possible approach:

1. Create a new class called NewApp. It includes a constructor which can take an instance of MyApp  
2. Iterate all the MyApps to create the NewApps  
3. Iterate all the old_app instances and -    
    1. Find all the instances of persistent pointers to that MyApp instances in the pool and do this: my_app.raw_ptr()->off = new_app.raw_ptr()->off (how?)
    2. Free the my_app instance 
    3. Iterate all the NewApp instances and set their type_num to the type_num of the old MyApp (how?)
4. In code, remove the old class and change the name of the NewApp class to MyApp so that all existing code references to MyApp now refers to the new objects

Before I go too far, what aspects of the above are not possible in the libpmemobj++ and libpmemobj APIs at present? I can see challenges in:
* 3.i finding all existing persistent_ptr<MyApp> in the pool. These could be scattered.
    * At first I thought I could find persistent_ptr<MyApp>'s as a type within the pool using POBJ_FIRST_TYPE_NUM, but it seems its not a persisted type?
    * What about if we wrapped this in our own custom class... then we could use POBJ_FIRST_TYPE_NUM to find all instances? Or something like shared_ptr but with reference tracking
* 3.iii how to set the type_num of the new class? It seems to be in the `extra data` part of memory_block? Or could we overload the type_num function when constructing the NewApp instances to set them to the old_num up front?
* How to do this transactionally and keep track of progress so we can restart if failure
* If we need to update code of existing objects to make use of the new class, how far can we go before invalidating layout anyway ([ref](https://github.com/pmem/libpmemobj-cpp/issues/374#issuecomment-642397959) re understanding text segment vs executable code storage)

It seems like a lot of work, but so is dumping and reloading terabytes of the entire pool/s just to change one object implementation. It's quite common for production databases to be upgraded in-place via SQL patch scripts for example. 

Another reason for potentially avoiding the root object chain is to support static inheritance via templates... but this needs some more research :-)

Thoughts? Alternatives?

**Comment by igchor** [comment]
1. Adding a new class

>*  What is the time complexity of POBJ_FIRST_TYPE_NUM and POBJ_NEXT_TYPE_NUM? It seems like it was iterating all PMEMoid's in the pool (ref)?

Yes, it iterates over the entire pool. It finds the objects by looking at the allocator bitmap for every allocated memory block. I guess it's linear to the number of allocated runs (@pbalcer correct me if I'm wrong).

> * Are there any other downsides to accessing class objects this way vs through the root object chain?

You can't use that for cases where you don't have type-id (like allocations without the header). And I would say it's more error prone. You basically have to keep all references in code, rather than as members in the root object.

I'm not sure if you're aware but it's possible to resize the root object. In C API you can use pmemobj_root function and specify larger size: https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_root.3

I belive that resizing the root is the best option here.

**Comment by pbalcer** [comment]
Given two types A and B, where B is the next version of A and that have a mapping function A -> B, you can construct a simple accessor method inside of a transaction (pseudo-code):
```
  fn accessor<T>(persistent_ptr<T> *t) -> T * {
     if t->type_num() != T::type_num() {
        persistent_ptr<T> old = *t;
        *t = T::from(old);
        delete_persistent(old);
     }
     return t->get();
  }
  fn from<T>(persistent_ptr<T> *t) {
     switch (t->type_num()) {
        case B::type_num():
        return B::map(t);
        break;
     }
  }
```

You can do this lazily while accessing objects at the cost of one (unlikely) condition. The problem then becomes computing stable type_nums...

**Comment by pbalcer** [comment]
Builtin object iterators must traverse the entire heap to locate all instances of a type. You can do that, but I'd recommend doing it once and matching the type numbers inside of the loop. Otherwise, you'd need to loop through the entire heap for every type.

SQL and similar store data in tables. The equivalent in libpmemobj++ would be to only store instances of a given type in some container and, when updating, iterating only through that container.
