### ISSUE TITLE
Doxygen Class index webpage is not properly formatted 

### ISSUE THREAD

**Issue by karczex** [pmem/libpmemobj-cpp#854]
# ISSUE: Doxygen Class index webpage is not properly formatted 

## Please provide a reproduction of the bug:

Just go to https://pmem.io/libpmemobj-cpp/master/doxygen/classes.html

## How often bug is revealed:
always

## Actual behavior:
The page is messy. 

Methods links do not fit into web page layout.

**Comment by lukaszstolarczuk** [comment]
for future references: Doxygen's configuration options are listed here:
https://www.doxygen.nl/manual/config.html#cfg_alphabetical_index

**Comment by lukaszstolarczuk** [comment]
Fixed in #858
