### ISSUE TITLE
Constructor description and behavior mismatch

### ISSUE THREAD

**Issue by KFilipek** [pmem/libpmemobj-cpp#869]
# ISSUE: Constructor description and behavior mismatch

## Actual behavior:

Currently underlying _allocate_ function will allocate amount of bytes represented by _count_ argument, despite data size.

## Expected behavior:

Description tells that: _Construct the container with **count copies of elements** with value ch._
So I've expect that it's true for type _char_, but with _wchar_t_ will fail, because 100 elements of type _wchar_t_ require twice as _char_.

## Details

```
/**
 * Construct the container with count copies of elements with value ch.
 *
 * @param[in] count number of elements to construct.
 * @param[in] ch value of all constructed elements.
 *
 * @pre must be called in transaction scope.
 *
 * @throw pmem::pool_error if an object is not in persistent memory.
 * @throw pmem::transaction_alloc_error when allocating memory for
 * underlying storage in transaction failed.
 * @throw pmem::transaction_scope_error if constructor wasn't called in
 * transaction.
 */
template <typename CharT, typename Traits>
basic_string<CharT, Traits>::basic_string(size_type count, CharT ch)
{
	check_pmem_tx();
	sso._size = 0;

	allocate(count);
	initialize(count, ch);
}
```

Are you willing to submit a pull request with a proposed change? 
Yes

Requested priority: High

**Comment by igchor** [comment]
If you look at the allocate() implementation you will see that it actually calls vector<CharT>::reserve(capacity + 1) which will allocate (capacity + 1) * sizeof(CharT) bytes. So, this is just a documentation error - we should fix the allocate() description.
