### ISSUE TITLE
inline_string.hpp is not copied to install prefix when radix tree is not installed

### ISSUE THREAD

**Issue by nisargshah95** [pmem/libpmemobj-cpp#955]
# ISSUE: inline_string.hpp is not copied to install prefix when radix tree is not installed

## Environment Information

- libpmemobj-cpp version(s):                              Latest master (commit 55351ae)
- PMDK (libpmemobj) package version(s):                              1.9
- OS(es) version(s):                                                 Fedora 30
- kernel version(s):                                                 5.0.9-301.fc30.x86_64
- compiler, libraries, packaging and other related tools version(s): gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

and possibly:
- TBB version(s):                                                    2019.8-3.fc30
- ndctl version(s):                                                  68-1.fc30

## Please provide a reproduction of the bug:
Install libpmemobj-cpp using the following commands -
```
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_RADIX_TREE=0 -DTEST_RADIX_TREE=0 ..
make && make install
```
Add the following line in your program and compile:
```
#include <libpmemobj++/container/concurrent_hash_map.hpp>
```

## How often bug is revealed:

always

## Actual behavior:

When `libpmemobj++/container/concurrent_hash_map.hpp` is included in a program, I get the following error:
```
In file included from /usr/local/include/libpmemobj++/container/concurrent_hash_map.hpp:16,
                 from bench.cpp:54:
/usr/local/include/libpmemobj++/detail/template_helpers.hpp:15:10: fatal error: libpmemobj++/experimental/inline_string.hpp: No such file or directory
   15 | #include <libpmemobj++/experimental/inline_string.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

## Expected behavior:

No compilation error.

## Details

`./include/libpmemobj++/experimental/inline_string.hpp`, which is required by `./include/libpmemobj++/detail/template_helpers.hpp`, which in turn is required by `./include/libpmemobj++/container/concurrent_hash_map.hpp` is not copied to the install prefix when radix tree installation is skipped.

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? No

Requested priority: Low

**Comment by lukaszstolarczuk** [comment]
Hi, thanks for posting your issue. We're wondering what would be the best fix and we come to conclusion that all of these `INSTALL_*` CMake options may be redundant and we could just install all files with no includes/excludes.

Can you @nisargshah95 please tell us if that would be ok with you? Or you rather want to have an CMake option to disable installation of e.g. radix related files?

**Comment by nisargshah95** [comment]
I disabled installation of radix tree because I was facing some compile-time errors with the templates in the radix tree code. I'm not sure if this just some issue with my system but I can check later and report any findings.

**Comment by igchor** [comment]
Thanks, we'd appreciate information about any compile-time errors. Btw, just installing the radix_tree should not cause any problems. The compiler error (if any) should appear only when you try to use the radix_tree. Wasn't that the case?

**Comment by nisargshah95** [comment]
Actually I just tried it out and was able to install radix tree without any problems. I think I faced the issue on an older Ubuntu 16.04 system which I no longer have access to, but I think it might have been due to older libraries on it.
