### ISSUE TITLE
concurrent_map_mt_gdb tests don't work on clang

### ISSUE THREAD

**Issue by igchor** [pmem/libpmemobj-cpp#968]
# ISSUE: concurrent_map_mt_gdb tests don't work on clang

## Environment Information

- libpmemobj-cpp version(s):                                         
- PMDK (libpmemobj) package version(s):                              
- OS(es) version(s):                                                 arch
- kernel version(s):                                                 
- compiler, libraries, packaging and other related tools version(s): 

- clang version: 10.0.1
- gdb version: 10.1

## Please provide a reproduction of the bug:

Run concurrent_mt_gdb tests

## How often bug is revealed:

always

## Actual behavior:

Test timeouts due to not hitting a breakpoint - rbreak does not seem to work.

## Expected behavior:

Test passes

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

**Comment by igchor** [comment]
https://github.com/pmem/libpmemobj-cpp/pull/967

**Comment by karczex** [comment]
Disable those tests for clang
