### ISSUE TITLE
Add concurrent_hash_map example with complex type

### ISSUE THREAD

**Issue by igchor** [pmem/libpmemobj-cpp#989]
# Add concurrent_hash_map example with complex type

## Rationale

Since concurrent_hash_map::insert does not work inside transactions it's not obvious how to insert complex types or pointers to persistent memory in a fail-safe manner.

## Description

The example should show how to store a pointer to some data (e.g. concurrent_hash_map<int, persistent_ptr<data>>) and some complex data structures (e.g. concurrent_hash_map<int, pmem::obj::vector<int>).

**Comment by seghcder** [comment]
This seems done?

**Comment by igchor** [comment]
Yes, this is done
